### ISSUE TITLE
Why the SPI SS pins in the source code are different?

### ISSUE THREAD

**Issue by CMUBOB97** [m5stack/M5-StickT#4]
Hello developers of M5StickT,

I purchased your product M5StickT and it is very impressive. I am working on this open source code and trying to add some extensions.

When reading the source code, I noticed that in the main ino file line 38, lepton is initialized as:

`Lepton lepton(21, 22, 0, 38);`

where from the documentation in lepton.h, these four pins corresponds to:
GPIO 21 -> SDA
GPIO 22 -> SCL
GPIO 0   -> SPI SS
GPIO 38 -> Vsync

However, after reading lepton.cpp, there is a SPI begin function in line 65 says:
`lepton_spi->begin(2, 25, 34, 35);`

According to the documentation in [ESP32 arduino library](https://github.com/espressif/arduino-esp32/blob/master/libraries/SPI/src/SPI.h) (SPI.h), these four pins are:
GPIO 2   -> SCK
GPIO 25 -> MISO
GPIO 34 -> MOSI
GPIO 35 -> SPI SS

Clearly GPIO 0 is not the same as GPIO 35. After that point, in functions `Lepton::syncFrame()` and `Lepton::end()`, the SPI SS pin used is still GPIO 0, defined originally in `Lepton lepton(21, 22, 0, 38);`. Could you explain why we have this conflict in the SPI SS pin definition? Thank you!

If you want to respond to this issue privately, my email address is chig@andrew.cmu.edu. Also feel free to explain things to me in Chinese or English.

**Comment by icyqwq** [comment]
你好，因为我使用的是软件片选（未使用SPI外设的片选），所以在声明类时指定的片选是有效的。至于为什么spi->begin又指定了一个片选，是因为在Arduino库中即使未使用的引脚也必须指定一个pin，否则会使用默认的pin（我不知道现在修复了没有）。所以35只是我随便选了一个未使用的引脚而已。

**Comment by CMUBOB97** [comment]
感谢您的回答！

如果不麻烦的话，请问您知道esp32和esp32s2的区别吗？

我现在把esp32s2和lepton
3.0建立了连接，esp32s2用的是FSPI，但是m5的代码并不能运行。如果您有任何建议的话，这对我的项目是非常有帮助的！

祝您今天工作顺利，
高驰

icyqwq ***@***.***> 于 2022年7月21日周四 下午9:47写道：
